<h2 style= "color:blue; text-align:left; "> <i>Register your name and email</i></h2>

<?php echo $this->tag->form("signup/register"); ?>
<body style="background:gray;">

    <p>
        <label for="name">Name</label>
        <?php echo $this->tag->textField("name"); ?>
    </p>

    <p>
        <label for="email">E-Mail</label>
        <?php echo $this->tag->textField("email"); ?>
    </p>

    <p>
        <?php echo $this->tag->submitButton("register"); ?>
    </p>

</form>
</body>